name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'  # Use the appropriate .NET version for your project

    - name: Restore dependencies
      run: dotnet restore src/YourProject.sln

    - name: Build
      run: dotnet build src/YourProject.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test src/YourProject.sln --no-restore --verbosity normal
